---
name: "Publish to NPM"
on:
  release:
    types:
      - "published"

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache-dependency-path: ./yarn.lock
          cache: "yarn"
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn run-instance
      
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - run: "npm version ${VERSION} --no-git-tag-version --allow-same-version"
      
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
